# -*- coding: utf-8 -*-
"""Final Project_1301204330_1301204317.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1epYBtAdpIDrr8dWXot62-ZamVjo40NmC

#Final Project

Fadil Rifaldy - 1301204330

M Faisal Zaenudin - 1301204317

IF-43-PIL-DS02

Buatlah visualisasi interaktif pada suatu data tertentu (case bebas) yang menunjukkan paling tidak harus ada interaktif slider dan select. App dideploy di heroku atau platform yang lain.

#IMPORT LIBRARY
"""

#import library yang dibutuhkan

from bokeh.io import output_notebook, curdoc
from bokeh.io import output_file, show
from bokeh.plotting import figure, show
from bokeh.models.widgets import Tabs, Panel
from bokeh.models import ColumnDataSource, GroupFilter, CDSView, HoverTool, Div
from bokeh.layouts import column, widgetbox
import pandas as pd
import numpy as np

#import dataset serta menampilkan 5 dataset pertama

dataframe = pd.read_csv("SahamMNCBank.csv", parse_dates = ["Date"])
dataframe = dataframe.rename(columns={"Ratio(%)" : 'Ratio'})
dataframe['Index']= dataframe.index + 1
dataframe.head()

"""#Sortir data"""

#sortir data
data = ColumnDataSource(dataframe)
data_mnc = CDSView(source=data)

#seting info lingkaran

circle_data = {'source': data, 'size': 3, 'alpha': 0.7, 'selection_color':'black'}

circle_mnc = {'view': data_mnc, 'color': 'blue', 'legend_label': 'MNC Bank'}

"""#Figure Close"""

#membuat figure
output_notebook()
select_tools = ['pan', 'box_select', 'wheel_zoom', 'tap', 'reset']
fig1 = figure(title= 'Close Data',x_axis_type='datetime',x_axis_label='Date', y_axis_label= 'Close',
              plot_height=500, plot_width=800, toolbar_location="right",tools=select_tools)

#menambahkan data lingkaran
fig1.circle(x='Date', y='Close', **circle_data, **circle_mnc)

#menambahkan arah
tooltips= [('Name','MNC Bank'),('Close', '@Close') ]
hover_glyph = fig1.circle(x='Date', y= 'Close' , source=data,size=3, alpha=0, hover_fill_color='black', hover_alpha=0.5)
fig1.add_tools(HoverTool(tooltips=tooltips, renderers=[hover_glyph]))

#menyembunyikan data via legend(level 3)
fig1.legend.click_policy = 'hide'
fig1.legend.location= 'top_right'

"""#Figure Volume"""

#membuat figure
output_notebook()
select_tools = ['pan', 'box_select', 'wheel_zoom', 'tap', 'reset']
fig2 = figure(title= 'Volume Data',x_axis_type='datetime',x_axis_label='Date', y_axis_label= 'Volume',
              plot_height=500, plot_width=800, toolbar_location="right",tools=select_tools)

#menambahkan data lingkaran
fig2.circle(x='Date', y='Volume', **circle_data, **circle_mnc)

#menambahkan arah
tooltips= [('Name','MNC Bank'),('Volume', '@Volume') ]
hover_glyph = fig2.circle(x='Date', y= 'Volume' , source=data,size=3, alpha=0,hover_fill_color='black', hover_alpha=0.5)
fig2.add_tools(HoverTool(tooltips=tooltips, renderers=[hover_glyph]))

#menyembunyikan data via legend(level 3)
fig2.legend.click_policy = 'hide'
fig2.legend.location= 'top_right'

"""#Figure Ratio

"""

#membuat figure
output_notebook()
select_tools = ['pan', 'box_select', 'wheel_zoom', 'tap', 'reset']
fig3 = figure(title= 'Ratio Data',x_axis_type='datetime',x_axis_label='Date', y_axis_label= 'Ratio',
              plot_height=500, plot_width=800, toolbar_location="right",tools=select_tools)

#menambahkan data lingkaran
fig3.circle(x='Date', y='Ratio', **circle_data, **circle_mnc)

#menambahkan arah
tooltips= [('Name','MNC Bank'),('Ratio', '@Ratio %') ]
hover_glyph = fig3.circle(x='Date', y= 'Ratio' , source=data,size=3, alpha=0,hover_fill_color='black', hover_alpha=0.5)
fig3.add_tools(HoverTool(tooltips=tooltips, renderers=[hover_glyph]))

#menyembunyikan data via legend(level 3)
fig3.legend.click_policy = 'hide'
fig2.legend.location= 'top_right'

"""#Configure Panel"""

# membuat file html
output_file('Visualisasi Saham MNC Bank.html', title='Visualisasi Saham MNC Bank')

#menambahkan title
isi = """<h1>Fluktuasi Harga Saham MNC Bank 2014 - 2021</h1>
<h3><i>Click Legend to HIDE Data</i><h3>"""
title = Div(text=isi)

#tambahkan panel widget dan tab
fig1_panel = Panel(child=fig1, title='Close Data')
fig2_panel = Panel(child=fig2, title='Volume Data')
fig3_panel = Panel(child=fig3, title='Ratio Data (%)')
tab = Tabs(tabs=[fig1_panel, fig2_panel, fig3_panel])

#tambahkan layout
show(column(title,tab))